try:
    x = int(input('Digite um número: '))
except ValueError:
    print('Entre com um número válido.')
